version: "3.8"

services:
  goapp:
    container_name: goapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app:rw
    environment:
      - GIN_MODE=release